# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/
---
APPLY_FIXES: none
DISABLE:
  - COPYPASTE
  - SPELL

DIABLE_LINTERS:
  - PYTHON_PYLINT
  - TERRAFORM_TERRASCAN

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
FILTER_REGEX_INCLUDE: "(src/|\\.cicd/|\\.github/|\\./.*\\.yml|\\./.*\\.yaml|\\./.*\\.md)"
FILTER_REGEX_EXCLUDE: "(megalinter-reports/)"
